#!/bin/bash

# Install base packages
yes | sudo apt-get install python-pip python-virtualenv python-dev libpq-dev 

echo "Are you going to use mysql for your database? [N/y]"
read INSTALL_MYSQL

if [[ "$INSTALL_MYSQL" == "y" ]]
then
    # Install mysql related packages
    yes | sudo apt-get install libmysqlclient-dev python-mysqldb
    echo 'MySQL-python' >> install/requirements.pip
fi
