# -*- coding: utf-8 -*-
"""
This document defines choices to be used on the models
"""

AREA_CODES = (
    (35, 'ALGARROBO'),
    (65, 'ANCUD'),
    (45, 'ANGOL'),
    (55, 'ANTOFAGASTA'),
    (41, 'ARAUCO'),
    (58, 'ARICA'),
    (42, 'BULNES'),
    (55, 'CALAMA'),
    (52, 'CALDERA'),
    (73, 'CAUQUENES'),
    (52, 'CHAÑARAL'),
    (42, 'CHILLAN'),
    (67, 'COHAIQUE'),
    (41, 'CONCEPCION'),
    (71, 'CONSTITUCION'),
    (52, 'COPIAPO'),
    (51, 'COQUIMBO'),
    (75, 'CURICO'),
    (51, 'ELQUI'),
    (57, 'IQUIQUE'),
    (33, 'LA LIGUA'),
    (51, 'LA SERENA'),
    (64, 'LA UNION'),
    (43, 'LAJA'),
    (53, 'LIMARÍ'),
    (73, 'LINARES'),
    (65, 'LLANQUIHUE'),
    (34, 'LOS ANDES'),
    (43, 'LOS ANGELES'),
    (53, 'LOS VILOS'),
    (33, 'OLMUE'),
    (64, 'OSORNO'),
    (53, 'OVALLE'),
    (65, 'PALENA'),
    (63, 'PANGUIPULLI'),
    (58, 'PARINACOTA'),
    (73, 'PARRAL'),
    (57, 'POZO AL MONTE'),
    (45, 'PUCON'),
    (65, 'PUERTO MONTT'),
    (61, 'PUNTA ARENAS'),
    (33, 'QUILLOTA'),
    (32, 'QUILPUE'),
    (72, 'RANCAGUA'),
    (64, 'RIO BUENO'),
    (35, 'SAN ANTONIO'),
    (34, 'SAN FELIPE'),
    (2, 'SANTIAGO'),
    (71, 'TALCA'),
    (41, 'TALCAHUANO'),
    (45, 'TEMUCO'),
    (63, 'VALDIVIA'),
    (32, 'VALPARAISO'),
    (75, 'VICHUQUEN'),
    (45, 'VICTORIA'),
    (32, 'VIÑA DEL MAR'),
)
